name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Features"
    labels: ["feat", "feature"]
  - title: "Fixes"
    labels: ["fix", "bug"]
  - title: "Refactor"
    labels: ["refactor"]
  - title: "Performance"
    labels: ["perf"]
  - title: "Docs"
    labels: ["docs"]
  - title: "Tests"
    labels: ["test"]
  - title: "Chore"
    labels: ["chore", "build", "ci", "style"]

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: ["breaking", "major"]
  minor:
    labels: ["feat", "feature", "minor"]
  patch:
    labels:
      [
        "fix",
        "bug",
        "chore",
        "docs",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "style",
        "patch",
      ]
  default: patch

autolabeler:
  - label: "feat"
    title:
      - '/^feat(\(.+\))?!?:/i'
  - label: "fix"
    title:
      - '/^fix(\(.+\))?!?:/i'
  - label: "chore"
    title:
      - '/^chore(\(.+\))?!?:/i'
  - label: "docs"
    title:
      - '/^docs(\(.+\))?!?:/i'
  - label: "refactor"
    title:
      - '/^refactor(\(.+\))?!?:/i'
  - label: "test"
    title:
      - '/^test(\(.+\))?!?:/i'
  - label: "perf"
    title:
      - '/^perf(\(.+\))?!?:/i'
  - label: "breaking"
    title:
      - '/^[a-z]+(\(.+\))?!:/'

template: |
  ## What's changed

  $CHANGES

  **Full changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
